spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/interview_im?createDatabaseIfNotExist=true
    username: root
    password: Baiks@123
    hikari:
      auto-commit: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
logging:
  level:
    web: DEBUG
    root: DEBUG
kafka:
  producer:
    bootstrap-servers: "localhost:9092"
    key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
    value-serializer: "org.apache.kafka.common.serialization.StringSerializer"